### ISSUE TITLE
The meaning of Didi for most mandarin speakers

### ISSUE THREAD

**Issue by insidewhy** [adam-cyclones/didi#57]
The word "didi" means "younger brother" in Mandarin, but is commonly used as a colloquialism for "penis".

Just throwing this out there: maybe it's not the most inclusive name for a project.

**Comment by insidewhy** [comment]
Also consider this from the top of the readme:

"didi is not ready for production however you can still take didi for a spin!"

Oh dear.

**Comment by adam-cyclones** [comment]
A name change would be **hard**, oh dear. I fear that any word is going to mean something hilarious in another language.

In france, people use the term, POO instead of OOP and that to me is funny but I understand the translation is just one of those things. What would you do in my shoes?

**Comment by adam-cyclones** [comment]
closing, I will look into alternatives.
